version: '3'
services:
    web:
        build: .
        depends_on:
            - db
        ports:
            - "3000:3000"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - ".rustwide:/home/cratesfyi/rustwide"
            - "cratesio-index:/opt/docsrs/prefix/crates.io-index"
        environment:
            CRATESFYI_RUSTWIDE_WORKSPACE: /home/cratesfyi/rustwide
            CRATESFYI_DATABASE_URL: postgresql://cratesfyi:password@db
        env_file:
            - .env
    db:
        image: postgres:alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: cratesfyi
            POSTGRES_PASSWORD: password
volumes:
    postgres-data: {}
    cratesio-index: {}
