---
name: Crate Build Failure
description: My crate failed to build in docs.rs.
labels: build-failure
body:
  - type: markdown
    attributes:
      value: |
        If you need a system dependency added for your crate to build,
        consider making a PR to https://github.com/rust-lang/crates-build-env
        instead of opening an issue here. There are detailed instructions for
        this at https://forge.rust-lang.org/docs-rs/add-dependencies.html.
  - type: input
    attributes:
      label: crate name
    validations:
      required: true
  - type: input
    attributes:
      label: build failure link
    validations:
      required: true
  - type: textarea
    attributes:
      label: additional details
